# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f751fa720a18be9d4c6397aed4e11628f1f666d35cd0e503597a24a79f2fe19d88a9c96314451f87ecb2b9550bcda9954501582686e4159d0b5836e50b5aaa64

test:
  secret_key_base: 28b1e64157374d5b9ea5d5a20c086e71104938f62a6cc5e3269916208a33c1e3fbd66c9b6f5794a8ccae06cc069bf413f574f224299328a0d05c808b72f21438

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
